### ISSUE TITLE
Not compatible with IntelliJ IDEA 2023.3

### ISSUE THREAD

**Issue by ofry** [SourceLabOrg/PhpDataObjectGeneratorPlugin#1]
PHP Data Object Generator 2021.1.14 (latest version) compatibility range: 212—232.*

Supported Products

PhpStorm — 2021.2 — 2023.2.4

IntelliJ IDEA Ultimate — 2021.2 — 2023.2.5

**Comment by Crim** [comment]
Whoops, I've uploaded an updated version and it is pending review.  Should be available in 12-36 hours depending on how quickly it gets reviewed.

Sorry about that!
